# [START cloudbuild]
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/shopping-cart-app:$SHORT_SHA'
  - '.'


- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/shopping-cart-app:$SHORT_SHA'
# [END cloudbuild]